framework:
    messenger:
        serializer:
            default_serializer: App\Messenger\Transport\JsonSerializer
        transports:
            match.api.to.match: "%env(MATCH_API_TO_MATCH)%"
            match.to.calculation: "%env(MATCH_TO_CALCULATION)%"
            match.to.app: "%env(MATCH_TO_APP)%"
        routing:
            'App\DataTransferObject\MatchDetailDataProvider':
                - match.api.to.match
            'App\DataTransferObject\MatchListDataProvider':
                - match.to.calculation
